version: '3.3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8042:8000"

  code:
    build:
      context: .
    environment:
      _LAMBDA_SERVER_PORT: 8080
    ports:
      - 8001:9000
    command: ["/main", "code"]