version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notifi
      MYSQL_USER: notifi
      MYSQL_PASSWORD: notifi
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-proot"]
      timeout: 20s
      retries: 10

  redis:
    image: "redis:alpine"
    ports:
      - "127.0.0.1:6379:6379"