version: '3.2'
services:
  db:
    image: mysql:5.6
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notifi
      MYSQL_USER: notifi
      MYSQL_PASSWORD: notifi
    tty: true

  REDIS_HOST:
    image: "redis:alpine"
    ports:
      - "127.0.0.1:6379:6379"

#  app:
#    image: maxisme/notifi-backend:latest
#    restart: always
#    environment:
#      db: notifi:notifi@tcp(db:3306)/notifi
#      sentry_dsn: ${sentry_dsn}
#      SERVER_KEY: ${SERVER_KEY}
#      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
#      redis: "redis:6379"
#    tty: true
#    ports:
#      - "9081:8080"
#    depends_on:
#      - db
#      - redis
#    links:
#      - db
#      - redis

  # helpers
  migrate:
    image: migrate/migrate
    network_mode: "host"
    volumes:
      - ./sql:/migrations/
    command: ["-path", "/migrations/", "-database", "mysql://notifi:notifi@tcp(127.0.0.1:3306)/notifi", "up"]