ingress:
  match: "Host(`notifi.it`) && (Path(`/ws`) || Path(`/code`))"

image:
  repository: "maxisme/notifi-backend"

envSecretRef: "notifi" # kubectl create secret generic notifi --from-env-file .env

pg:
  enabled: true