version: '3.8'
services:
  app:
    image: maxisme/notifi-backend:${TAG:?err}
    env_file:
      - "${ENV_FILE:?err}"
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${SUBDOM}notifi-backend.rule=Host(`${SUBDOM}s.notifi.it`) || (Host(`notifi.it`) && Path(`/${SUBDOM}api`))"
        - "traefik.http.services.${SUBDOM}notifi-backend.loadbalancer.server.port=8080"
        - "traefik.http.routers.${SUBDOM}notifi-backend.middlewares=404"
    networks:
      - traefik
      - db

  migrate:
    image: migrate/migrate
    networks:
      - db
    command: ["-source", "${MIGRATE_SRC:?err}", "-database", "mysql://${DB_HOST:?err}", "up"]
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: none

networks:
  traefik:
    external: true
  db:
    external: true